In [3]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
import torch

n_embeddings = 256
embedding_dim = 32

init_bound = 1 / n_embeddings
embedding = torch.Tensor(n_embeddings, embedding_dim)
embedding.uniform_(-init_bound, init_bound)
print(embedding)
embedding = embedding / (torch.norm(embedding, dim=1, keepdim=True) + 1e-4)

tensor([[-0.0035,  0.0012, -0.0003,  ..., -0.0026, -0.0013, -0.0019],
        [-0.0006,  0.0015,  0.0029,  ..., -0.0028, -0.0008, -0.0027],
        [ 0.0018,  0.0015,  0.0020,  ...,  0.0032,  0.0005,  0.0021],
        ...,
        [ 0.0010, -0.0007, -0.0017,  ...,  0.0039, -0.0032, -0.0016],
        [ 0.0020,  0.0011, -0.0006,  ...,  0.0015,  0.0004, -0.0026],
        [-0.0003,  0.0023,  0.0017,  ..., -0.0013,  0.0018,  0.0029]])


In [4]:
embedding

tensor([[-0.2640,  0.0903, -0.0197,  ..., -0.1947, -0.0939, -0.1453],
        [-0.0426,  0.1114,  0.2170,  ..., -0.2114, -0.0586, -0.2054],
        [ 0.1581,  0.1318,  0.1771,  ...,  0.2817,  0.0439,  0.1781],
        ...,
        [ 0.0867, -0.0667, -0.1496,  ...,  0.3521, -0.2926, -0.1483],
        [ 0.1772,  0.0954, -0.0509,  ...,  0.1317,  0.0320, -0.2283],
        [-0.0257,  0.1928,  0.1408,  ..., -0.1073,  0.1512,  0.2463]])

In [5]:

kmeans = KMeans(n_clusters=40, random_state=1)
df = pd.DataFrame(embedding.numpy())
print(df)

kmeans.fit(df)

           0         1         2         3         4         5         6   \
0   -0.263977  0.090274 -0.019653  0.015394  0.104608  0.151828  0.257137   
1   -0.042586  0.111410  0.216992  0.051540  0.065972  0.024605  0.224489   
2    0.158087  0.131807  0.177097  0.014052 -0.007378 -0.226524 -0.047297   
3   -0.135522  0.209422 -0.048426  0.234386  0.221735 -0.265745  0.199242   
4   -0.013300  0.189537 -0.039668  0.155829  0.175629  0.114510  0.338451   
..        ...       ...       ...       ...       ...       ...       ...   
251 -0.263648 -0.048756 -0.080871 -0.295507 -0.226725  0.177153 -0.249978   
252  0.275485  0.277596 -0.111962  0.175049 -0.169297 -0.007246 -0.069175   
253  0.086681 -0.066660 -0.149648 -0.044304 -0.249949 -0.064966  0.101827   
254  0.177183  0.095360 -0.050942 -0.215652  0.150750 -0.277182  0.241537   
255 -0.025657  0.192829  0.140837  0.126141 -0.050089  0.118799  0.229041   

           7         8         9   ...        22        23        24  \
0  

KMeans(n_clusters=40, random_state=1)

In [6]:
kmeans.labels_

array([35, 18,  1, 33, 29, 19, 23, 23, 27, 27, 22,  6, 11, 24,  2, 38, 17,
        8, 28, 30, 27, 31, 30, 20, 39, 31,  6, 22, 12, 11, 20, 29, 23, 24,
        3, 29,  1, 36, 36,  5, 28, 22,  6, 31, 26,  6,  1,  2, 16, 30, 39,
       21,  3, 14,  7, 22, 33, 17, 35,  6, 32,  8, 15, 10, 21, 10,  7, 39,
       24, 36,  0, 16, 32, 26, 24,  6, 13, 16, 37, 10, 34, 34, 10,  4, 12,
       14, 34,  0, 21, 10, 33, 30,  0, 27,  0, 12, 35, 22, 11,  0, 26,  9,
        5, 34, 37, 33,  0,  1, 28,  4, 38, 29, 19, 17, 19,  9,  9, 21, 21,
       28,  0,  9,  5, 16,  9, 37,  8, 36, 39,  3,  3, 38, 14, 25, 18, 22,
       25,  7, 24, 13, 25, 17, 24, 16, 31,  8, 11, 32, 33, 15, 25, 32, 21,
       36, 18, 10, 27,  1, 17, 16, 17, 29, 35, 18, 30, 29, 23, 22, 34,  7,
       22, 24, 26,  2,  5,  0, 17,  5, 18, 13, 12, 30, 17,  9, 24,  8, 33,
       39, 17, 37, 27,  1, 16, 12, 36,  8,  4,  1,  5,  8, 37, 17, 23, 31,
       37,  4, 38, 15,  3, 37, 27, 24,  4, 13, 23, 26, 29, 31,  4, 28,  2,
       13, 20,  1,  7, 25

In [7]:
kmeans.cluster_centers_

array([[ 0.13710833,  0.13555494, -0.00705492, ..., -0.06749367,
         0.05083771,  0.06643082],
       [ 0.10126361,  0.08141163,  0.09722292, ...,  0.17511825,
        -0.09129256, -0.06892052],
       [-0.13707572,  0.04151579, -0.08462971, ...,  0.1887199 ,
        -0.07752898, -0.1457755 ],
       ...,
       [-0.13896416,  0.11873512,  0.17327297, ..., -0.16246428,
         0.03137348,  0.17290284],
       [-0.10009202,  0.05401409,  0.13438177, ..., -0.25026742,
        -0.03075166,  0.07894172],
       [ 0.05844247, -0.16889001, -0.04494832, ...,  0.09092784,
        -0.05507362, -0.08464031]], dtype=float32)

# Make Codebook

In [1]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

In [2]:
titles, srcs, tgts = [], [], []
with open('/home/jinsung/Voice-Conversion/conversion_metas/VCTK_seen_pairs.txt', "r") as file:
    for rawline in file.readlines()[:]:
        title, tgt, src = rawline.strip().split("|")

        titles.append('src:'+src.split('/')[-1][:-4]+'&tgt:'+tgt.split('/')[-1][:-4])
        
        
        srcs.append(src)
        tgts.append(tgt)

        substring_to_replace1 = 'vctk-16k'
        replacement_string1 = 'wavlm-6L' 
        substring_to_replace2 = '.wav'
        replacement_string2 = '.pt' 
        
        ref_paths_new = [ref_path.replace(substring_to_replace1, replacement_string1).replace(substring_to_replace2, replacement_string2) for ref_path in srcs]
        src_paths_new = [src_path.replace(substring_to_replace1, replacement_string1).replace(substring_to_replace2, replacement_string2) for src_path in tgts]

In [3]:
flag=0
for path in ref_paths_new :
    tmp = torch.load(path)
    tmp = tmp.squeeze().transpose(0,1)
    if flag == 0:
        total = tmp
        flag = 1
    else:
        total = torch.concat((total, tmp), dim=0)
    

In [4]:
total = total / (torch.norm(total, dim=1, keepdim=True) + 1e-4)
df = pd.DataFrame(total.numpy())

In [6]:
total.shape

torch.Size([19772, 1024])

In [5]:
kmeans = KMeans(n_clusters=256, random_state=1)
kmeans.fit(df)

KMeans(n_clusters=256, random_state=1)

In [7]:
kmeans.cluster_centers_.shape

(256, 1024)

In [68]:
kmeans.cluster_centers_

array([[-0.00536272, -0.01522215, -0.02451737, ..., -0.01342722,
        -0.00310087, -0.01597626],
       [ 0.02262801, -0.01386118, -0.00375495, ...,  0.00189466,
         0.00547088, -0.0029685 ],
       [-0.00480938, -0.02068549,  0.0101621 , ..., -0.01078235,
        -0.00905266,  0.00229259],
       ...,
       [-0.00890913, -0.02424862,  0.00873988, ...,  0.00509309,
        -0.02517808, -0.00600876],
       [ 0.01164024, -0.00923089,  0.00367463, ..., -0.01545407,
        -0.00955019,  0.00185707],
       [-0.00646191, -0.01737179,  0.00242724, ..., -0.00327918,
        -0.0003539 , -0.00334529]], dtype=float32)

In [70]:
torch.save(torch.from_numpy(kmeans.cluster_centers_), 'codebook.pt')

# Test

In [121]:
from numpy.linalg import norm
codebook = torch.load('./codebook.pt')
input=codebook[3]

score = torch.matmul(codebook,input)/torch.norm(codebook, dim=1)
content_emb = codebook[torch.argmax(score)]
speaker_emb = input - content_emb

In [122]:
speaker_emb

tensor([0., 0., 0.,  ..., 0., 0., 0.])